### ISSUE TITLE
Catch panic in Raidman client when Riemann server isn't available

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap-plugin-publisher-riemann#2]
Looks like the Raidman client will panic if the Riemann server isn't available. This could be bad.

**Comment by IzabellaRaulin** [comment]
@geauxvirtual, is it still valid?

**Comment by geauxvirtual** [comment]
Yes. The plugin will panic if the server isn't available. https://gist.github.com/geauxvirtual/d406439f7c6a6cb6b2f7112cec80eae9
