### ISSUE TITLE
Update Publish to use Raidman multisend to send multiple events at once.

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap-plugin-publisher-riemann#3]

**Comment by mkleina** [comment]
:+1:

**Comment by mkleina** [comment]
@geauxvirtual, can you fix this issue? It seems that it can be fixed easily, just building slice of events and then using SendMulti() instead of Send()

**Comment by mbbroberg** [comment]
@mkleina hey, @geauxvirtual is not the maintainer of this plugin going forward and it's not a priority for the rest of the core maintainers. Feel free to hop in and fix this if you have time @mkleina!
